
<?php 
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Zend Framework Tutorial');

echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> 
<head>
    <?php echo $this->headMeta(); ?> 
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/styles/style.css')
    							->appendStylesheet($this->baseUrl().'/styles/flick/jquery-ui-1.8.9.custom.css'); ?>
    <?php echo $this->headScript();?>
</head>
<body>
<div class="header">
<img src="<?php echo $this->baseUrl().'/images/kalys-logo.jpg';?>" style="float:left;margin-right:40px"/>
<div class="title"><h1><?php echo $this->escape($this->title); ?></h1></div>
<div class="clearfloat"></div>
</div>
<div class="sidebar">
<div>
	<a href="<?php echo $this->url(array('controller'=>'index', 
		'action'=>'view-clients'), null, true);?>">View Clients</a>
	<a href="<?php echo $this->url(array('controller'=>'index', 
		'action'=>'add-client'), null, true);?>">Add new Client</a></div>
<div>
	<a href="<?php echo $this->url(array('controller'=>'index', 
		'action'=>'view-agents'), null, true);?>">View Agents</a>
	<a href="<?php echo $this->url(array('controller'=>'index', 
		'action'=>'add-agent'), null, true);?>">Add new Agent</a></div>
<div>
	<a href="<?php echo $this->url(array('controller'=>'index', 
		'action'=>'view-cities'), null, true);?>"><?php echo $this->translate('View Cities')?></a>
	<a href="<?php echo $this->url(array('controller'=>'index', 
		'action'=>'add-city'), null, true);?>">Add new City</a></div>
<div>
	<a href="<?php echo $this->url(array('controller'=>'index', 
		'action'=>'view-industries'), null, true);?>">View Industries</a>
	<a href="<?php echo $this->url(array('controller'=>'index', 
		'action'=>'add-industry'), null, true);?>">Add new Industry</a></div>
<div>
	<a href="<?php echo $this->url(array('controller'=>'index', 
		'action'=>'view-data-types'), null, true);?>">View Data Types</a>
	<a href="<?php echo $this->url(array('controller'=>'index', 
		'action'=>'add-data-type'), null, true);?>">Add new Data Type</a></div>
<div>
	<a href="<?php echo $this->url(array('controller'=>'index', 
		'action'=>'view-event-types'), null, true);?>">View Event Types</a>
	<a href="<?php echo $this->url(array('controller'=>'index', 
		'action'=>'add-event-type'), null, true);?>">Add new Event Type</a></div>
<div><a href="<?php echo $this->url(array('controller'=>'index', 
		'action'=>'search-clients'), null, true);?>">Search Client Database</a></div>
<div><a href="<?php echo $this->url(array('controller'=>'index', 
		'action'=>'export-clients'), null, true);?>">Export Database</a></div>
</div>
<div class="content">
    
    <?php echo $this->layout()->content; ?>
</div>
</body>
</html>