<?php 
$this->title = "Add new client";
$this->headTitle($this->title);

$script = '$(function() {
		$( "#city" ).autocomplete({
			source: "/index/city-list"
		});
	});';


$this->headLink()->appendStylesheet($this->baseUrl('styles/flick/jquery-ui-1.8.9.custom.css'));		
$this->headScript()
	->appendFile($this->baseUrl('js/jquery-1.4.4.min.js','text/javascript'))
	->appendFile($this->baseUrl('js/jquery-ui-1.8.9.custom.min.js','text/javascript'))
	->appendScript($script,'text/javascript');

?>



<table cellpadding="3" cellspacing="3" border="0">
	<tr>
		<td valign="top"><?php echo $this->form ;?></td>
	</tr>
</table>