<?php         
$this->title = "View Clients";
$this->headTitle($this->title);
?>

<table>
<tr>
    <th>Name</th>
    <th>Address</th>
    <th>Contact Person</th>
    <th>City</th>
    <th>Agent</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($this->clients as $client) : ?>
<tr>
    <td><?php echo $this->escape($client->name);?></td>
    <td><?php echo $this->escape($client->address);?></td>
    <td><?php echo $this->escape($client->contact_name);?></td>
    <td><?php echo $this->escape($this->cities[$client->city]);?></td>
    <td><?php echo $this->escape($this->agents[$client->agent_id]);?></td>
    <td>
        <a href="<?php echo $this->url(array('controller'=>'index', 
            'action'=>'edit-client', 'id'=>$client->id));?>">Edit</a>
        <a href="<?php echo $this->url(array('controller'=>'index', 
            'action'=>'delete', 'id'=>$client->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>