<?php         
$this->title = "View Data Types";
$this->headTitle($this->title);
?>

<table cellpadding="2" cellspacing="2" border="0">
<?php foreach($this->datatypes as $datatype) : ?>
<tr>
	<td><?php echo $this->escape($datatype->data_type_name);?></td>
    <td><a class="delete-icon" href="<?php echo $this->url(array('controller'=>'index', 
            'action'=>'delete-data-types', 'id'=>$datatype->id));?>">Delete</a></td>
</tr>
<?php endforeach; ?>
</table>

